### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by sharifsagar80** [JurijsNazarovs/bayesian_nn#1]
How we can use custom dataset with your model..I tried to implement but always getting after 1st epoch? can you guide me please

**Comment by JurijsNazarovs** [comment]
Hi,

There are 2 options:
1) if you use main.py in bayesian_dnn_class, then you should redefine you own DataLoader, which is refereed in the code as train_loader and val_loader. Here are more details on how to define your own custom data loader: https://pytorch.org/tutorials/beginner/data_loading_tutorial.html

2) if you have already some working network with working code to load your dataset, you can redefine your networks to make it bayesian, as we describe in the README, section "Bayesify your Neural Network". 

Also, if you meant that you used main.py and get stuck in the first epoch, please, redownload the code. There was a debug criteria, which stops the code. I removed it.
