### ISSUE TITLE
Out of memory problem

### ISSUE THREAD

**Issue by urnotmeeto** [JurijsNazarovs/bayesian_nn#2]
Hello, I am trying to run your code on my pc which has a 32GB RAM CPU and a 3GB GTX 1060 GPU. And I am using my own dataset with 100 * 7 images in total. However, I got 'Out Of Memory' error before the very first epoch for net like vgg11, even if the batch size is 1.
With CPU, the error is 
> RuntimeError: $ Torch: not enough memory: you tried to allocate 0GB. Buy new RAM! at ..\aten\src\TH\THGeneral.cpp:204

With GPU, the error is
> RuntimeError: CUDA error: out of memory

I wonder if it is a hardware problem, or is there some restriction for the input size of images for different NNs? If the first case, what will be the basic hardware requirement?

Thank you very much.

**Comment by JurijsNazarovs** [comment]
Hello,

Thanks for opening the issue.

Please note that when you use bayesian NN, number of parameters is usually doubled, which makes the network twice bigger. VGG11 is a big network by itself, and seems like you do not have enough space to get it inside GPU (but I would think it should be enough space to fit in 32GB ram, if you really have that much of available (free) ram). 

We ran our experiments on 11GB GPU, so, that was enough to fit all models.
To make sure that you set parameters correct:
1) Can you try to run smaller model, like ResNet-18 on GPU or CPU? Note: in paper, Figure 2 (right) gives you the estimate of the size of the network. (https://github.com/JurijsNazarovs/bayesian_nn/blob/main/paper.pdf)
2) Can you give more details on parameters you used  for: --approx_post, --kl_method, --n_mc_iter

**Comment by urnotmeeto** [comment]
Thanks for replying me so soon.

I have checked that before running the code, the free RAM of CPU is 31.8GB.

I tested ResNet-18, with the command `python soft.py --net PreActResNet18 --batch_size 1 --devices cpu --approx_post Gaus --kl_method direct`, but got the same errors. I have also tried the other --kl_method and --approx_post settings, yet none of them worked, for CPU and GPU.
("soft.py" is a copy of "main.py" except that the dataset is replaced)

The full output is: 

> 22330112
Compute KL divergence set to: True
Traceback (most recent call last):
  File "soft.py", line 581, in <module>
    main()
  File "soft.py", line 311, in main
    train_loader, model, optimizer, epoch)
  File "soft.py", line 387, in train
    output, kl = model(inputs)
  File "C:\Users\user\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\桌面\bayesian_nn\bayesian_dnn_class\models\resnet.py", line 181, in forward
    out, kl_ = layer[i](out)
  File "C:\Users\user\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\桌面\bayesian_nn\bayesian_dnn_class\models\resnet.py", line 59, in forward
    out, kl_ = self.conv1(out)
  File "C:\Users\user\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "..\bayes_layers.py", line 281, in forward
    output, kl = post.forward(self, x, fun="conv2d")
  File "..\vi_posteriors.py", line 260, in forward
    bias=None).to(x.device) + numer_eps
RuntimeError: $ Torch: not enough memory: you tried to allocate 13GB. Buy new RAM! at ..\aten\src\TH\THGeneral.cpp:204

Btw, I may try it again on the Cloud with more powerful hardwares.

**Comment by JurijsNazarovs** [comment]
Could you please try this:
`python soft.py --net PreActResNet18 --batch_size 1 --devices cpu --approx_post Gaus --kl_method repar --n_mc_iter 1 --n_test_iter 1` ?

**Comment by urnotmeeto** [comment]
Still the same output.

**Comment by JurijsNazarovs** [comment]
Alright, then the problem is not the Bayesian model, because with `--kl_method repar` it should not consume much memory. Do you think you might load all data together in your data loader, so that it occupies the whole memory?

**Comment by JurijsNazarovs** [comment]
There is a function `def train(train_loader, model, optimizer, epoch):` right after that line you can put a following code: `import pdb; pdb.set_trace()`, and run code again. It will stop before training starts in the debug mode. Then you can check your Ram/GPU memory to see if it is already occupied. If that is true, then you might need to change the way you load data.

**Comment by urnotmeeto** [comment]
While stopping before training starts in debug mode, the Ram memory is not fully occupied, with 20GB remained or so. But after training starts, it starts to be fully occupied.

I am loading the splitted data like this:
>
    data = {'Images': image, 'labels': labels}
    data = pd.DataFrame(data)
    lb = LabelEncoder()
    data['encoded_labels'] = lb.fit_transform(data['labels'])

    validation_split = 0.2
    shuffle_dataset = True
    random_seed = 42

    dataset_size = len(data)
    indices = list(range(dataset_size))
    split = int(np.floor(validation_split * dataset_size))
    if shuffle_dataset :
        np.random.seed(random_seed)
        np.random.shuffle(indices)
    train_indices, val_indices = indices[split:], indices[:split]

    train_sampler = SubsetRandomSampler(train_indices)
    valid_sampler = SubsetRandomSampler(val_indices)

    transform_train = transforms.Compose([transforms.ToTensor()])
    # transform_test = transforms.Compose([transforms.ToTensor()])

    dataset = Soft_Dataset(data, transform=transform_train)
    train_loader = torch.utils.data.DataLoader(dataset, batch_size=batch_size, sampler=train_sampler)
    val_loader = torch.utils.data.DataLoader(dataset, batch_size=batch_size, sampler=valid_sampler)

with the overrided Dataset class:

> 
class Soft_Dataset(torch.utils.data.Dataset):
    def __init__(self, img_data, transform=None):
        self.transform = transform
        self.img_data = img_data
        
    def __len__(self):
        return len(self.img_data)
    
    def __getitem__(self, index):
        img_name = self.img_data.loc[index, 'Images']
        image = Image.open(img_name)
        # image = image.convert('RGB')
        image = image.resize((224,224))
        label = torch.tensor(int(self.img_data.loc[index, 'encoded_labels']))
        if self.transform is not None:
            image = self.transform(image)
        return image, label

**Comment by JurijsNazarovs** [comment]
In the `def __getitem__`, can you resize image for (32, 32)? I understand that is not what you would like for your final goal, but just for sanity check, to see that it works with small images.

**Comment by urnotmeeto** [comment]
It works with the small images. Thank you! :)

**Comment by JurijsNazarovs** [comment]
Good! Then it seems that you do need a more powerful hardware to train on large images. Please, note that with Bayesian NN number of parameters is doubled compare to deterministic networks.

**Comment by JurijsNazarovs** [comment]
By the way, for your large images you can try to design your own Bayesian Neural Network (using our block in Readme), using UNET architecture or something similar. It will require much less memory,  depending on the number of skipped connections.  Or you can try to define smaller ResNet model (like ResNet6) in the end of `models/resnet.py`.
